# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predictor_view.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RoweTechPredictor(object):
    def setupUi(self, RoweTechPredictor):
        RoweTechPredictor.setObjectName("RoweTechPredictor")
        RoweTechPredictor.resize(1045, 874)
        self.centralWidget = QtWidgets.QWidget(RoweTechPredictor)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 291, 161))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 273, 120))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.deploymentDurationSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.deploymentDurationSpinBox.setMinimum(1)
        self.deploymentDurationSpinBox.setMaximum(9999)
        self.deploymentDurationSpinBox.setObjectName("deploymentDurationSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deploymentDurationSpinBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ceiDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.ceiDoubleSpinBox.setMaximum(99999.99)
        self.ceiDoubleSpinBox.setProperty("value", 1.0)
        self.ceiDoubleSpinBox.setObjectName("ceiDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ceiDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cwsSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.cwsSpinBox.setProperty("value", 35)
        self.cwsSpinBox.setObjectName("cwsSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cwsSpinBox)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cerecordCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cerecordCheckBox.setText("")
        self.cerecordCheckBox.setObjectName("cerecordCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cerecordCheckBox)
        self.subsystemConfigGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.subsystemConfigGroupBox.setGeometry(QtCore.QRect(20, 190, 291, 111))
        self.subsystemConfigGroupBox.setObjectName("subsystemConfigGroupBox")
        self.subsystemComboBox = QtWidgets.QComboBox(self.subsystemConfigGroupBox)
        self.subsystemComboBox.setGeometry(QtCore.QRect(10, 20, 271, 41))
        self.subsystemComboBox.setObjectName("subsystemComboBox")
        self.addSubsystemButton = QtWidgets.QPushButton(self.subsystemConfigGroupBox)
        self.addSubsystemButton.setGeometry(QtCore.QRect(170, 70, 113, 32))
        self.addSubsystemButton.setObjectName("addSubsystemButton")
        self.tabSubsystem = QtWidgets.QTabWidget(self.centralWidget)
        self.tabSubsystem.setEnabled(True)
        self.tabSubsystem.setGeometry(QtCore.QRect(320, 30, 671, 811))
        self.tabSubsystem.setObjectName("tabSubsystem")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabSubsystem.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabSubsystem.addTab(self.tab_4, "")
        self.predictionGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.predictionGroupBox.setGeometry(QtCore.QRect(20, 310, 291, 111))
        self.predictionGroupBox.setObjectName("predictionGroupBox")
        self.layoutWidget = QtWidgets.QWidget(self.predictionGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 291, 68))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.numBatteriesLabel = QtWidgets.QLabel(self.layoutWidget)
        self.numBatteriesLabel.setText("")
        self.numBatteriesLabel.setObjectName("numBatteriesLabel")
        self.gridLayout_2.addWidget(self.numBatteriesLabel, 1, 1, 1, 1)
        self.dataUsageLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dataUsageLabel.setText("")
        self.dataUsageLabel.setObjectName("dataUsageLabel")
        self.gridLayout_2.addWidget(self.dataUsageLabel, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.powerLabel = QtWidgets.QLabel(self.layoutWidget)
        self.powerLabel.setText("")
        self.powerLabel.setObjectName("powerLabel")
        self.gridLayout_2.addWidget(self.powerLabel, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 2, 0, 1, 1)
        self.commandFileGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.commandFileGroupBox.setGeometry(QtCore.QRect(20, 430, 291, 391))
        self.commandFileGroupBox.setObjectName("commandFileGroupBox")
        self.commandFileTextBrowser = QtWidgets.QTextBrowser(self.commandFileGroupBox)
        self.commandFileTextBrowser.setGeometry(QtCore.QRect(10, 40, 261, 301))
        self.commandFileTextBrowser.setObjectName("commandFileTextBrowser")
        self.saveCommandsButton = QtWidgets.QPushButton(self.commandFileGroupBox)
        self.saveCommandsButton.setGeometry(QtCore.QRect(0, 350, 113, 32))
        self.saveCommandsButton.setObjectName("saveCommandsButton")
        self.revLabel = QtWidgets.QLabel(self.centralWidget)
        self.revLabel.setGeometry(QtCore.QRect(20, 830, 291, 16))
        self.revLabel.setObjectName("revLabel")
        RoweTechPredictor.setCentralWidget(self.centralWidget)

        self.retranslateUi(RoweTechPredictor)
        self.tabSubsystem.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RoweTechPredictor)

    def retranslateUi(self, RoweTechPredictor):
        _translate = QtCore.QCoreApplication.translate
        RoweTechPredictor.setWindowTitle(_translate("RoweTechPredictor", "MainWindow"))
        self.groupBox.setTitle(_translate("RoweTechPredictor", "System Settings"))
        self.label.setText(_translate("RoweTechPredictor", "Deployment Duration (Days)"))
        self.label_2.setText(_translate("RoweTechPredictor", "CEI (s)"))
        self.label_3.setText(_translate("RoweTechPredictor", "CWS (ppt)"))
        self.label_4.setText(_translate("RoweTechPredictor", "Record To Internal SD Card"))
        self.subsystemConfigGroupBox.setTitle(_translate("RoweTechPredictor", "Subsystem Configurations"))
        self.addSubsystemButton.setText(_translate("RoweTechPredictor", "ADD"))
        self.tabSubsystem.setTabText(self.tabSubsystem.indexOf(self.tab_3), _translate("RoweTechPredictor", "Tab 1"))
        self.tabSubsystem.setTabText(self.tabSubsystem.indexOf(self.tab_4), _translate("RoweTechPredictor", "Tab 2"))
        self.predictionGroupBox.setTitle(_translate("RoweTechPredictor", "Prediction"))
        self.label_17.setText(_translate("RoweTechPredictor", "Num Batteries: "))
        self.label_16.setText(_translate("RoweTechPredictor", "Power Usage: "))
        self.label_29.setText(_translate("RoweTechPredictor", "Data Usage: "))
        self.commandFileGroupBox.setTitle(_translate("RoweTechPredictor", "Command File"))
        self.saveCommandsButton.setText(_translate("RoweTechPredictor", "Save to File"))
        self.revLabel.setText(_translate("RoweTechPredictor", "TextLabel"))

